language: python

dist: xenial

python:
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7'
    # - 'pypy'
    # - 'pypy3'
    - 'pypy3.5-6.0'

env:
    - DJANGO="django>=1.11,<2"
    - DJANGO="django>=1.11.17,<2.0"
    - DJANGO="django>=2.0,<2.1"
    - DJANGO="django>=2.1,<2.2"
    - DJANGO="django>=2.2,<3.0"
    - DJANGO="django>=3.0,<3.1"

install:
    - pip install ${DJANGO}
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt

script:
    - python manage.py test

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO="django>=1.11.17,<2.0"
    - python: "3.4"
      env: DJANGO="django>=2.1,<2.2"
    - python: "3.4"
      env: DJANGO="django>=2.2,<3.0"
    - python: "3.4"
      env: DJANGO="django>=3.0,<3.1"
    - python: "3.5"
      env: DJANGO="django>=1.11.17,<2.0"
    - python: "3.5"
      env: DJANGO="django>=3.0,<3.1"
    - python: "3.6"
      env: DJANGO="django>=1.11.17,<2.0"
    - python: "pypy3.5-6.0"
      env: DJANGO="django>=1.11.17,<2.0"
    - python: "3.7"
      env: DJANGO="django>=1.11,<2.0"
